version: '3'
services:
  db: &DB
    image: postgres:9.4.5
    ports:
      - 5432:5432
    #environment:
      #POSTGRES_USER: evergreen_db_user
      #POSTGRES_PASSWORD: P@$$W0rd
    volumes:
       - pgdata:/var/lib/postgresql/data

#dev:
  #build: .
  #command: sh -c "mix phoenix.server"
  #ports:
    #- 4000:4000
  #environment: &ENV
    #DATABASE_URL: ecto://evergreen_user:P@$$W0rd@db/evergreen_api_dev
  #depends_on:
    #- "db"
  #volumes:
      #- ./:/usr/src/app
  #links:
    #- db:db

#test:
  #build: .
  #command: sh -c "mix test"
  #environment:
    #DATABASE_URL: ecto://user:password@db/rest_api_test
  #volumes:
      #- ./:/usr/src/app
  #links:
    #- db:db

#version: "3"
#services:
  #db: &DB
    #image: postgres:9.4.5
    #ports:
      #- 5432:5432
    #environment:
      #POSTGRES_USER: user
      #POSTGRES_PASSWORD: password
      #POSTGRES_DB: hello_prod
    #volumes:
       #- pgdata:/var/lib/postgresql/data

  #prod:
    #build: .
    #ports:
      #- 8080:8080
    #environment: &ENV
      #DATABASE_URL: ecto://user:password@db/hello_prod
    #depends_on:
      #- "db"
    #links:
      #- db:db
volumes:
  pgdata:
