version: '3'
services:
  db: &DB
    image: postgres:9.4.5
    ports:
      - 5432:5432
    env_file: ./.env
    volumes:
       - pgdata:/var/lib/postgresql/data

  api:
    build: ./api/
    ports:
      - 4000:4000
    environment:
      DATABASE_URL: "ecto://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
    volumes:
      - ./api:/app
    depends_on:
      - "db"
    links:
      - db:db

#test:
  #build: .
  #command: sh -c "mix test"
  #environment:
    #DATABASE_URL: ecto://user:password@db/rest_api_test
  #volumes:
      #- ./:/usr/src/app
  #links:
    #- db:db

  webapp:
    build: ./webapp/
    ports:
      - 3000:3000
    environment:
      API_URL: "http://api"
    volumes:
      - ./webapp:/app
    depends_on:
      - "api"
    links:
      - api:api

volumes:
  pgdata:
